exports.cekResi = require('./cekResi')
exports.downloader = require('./downloader')
exports.removebg = require('./remove-bg')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.getLocationData = require('./location')